---
- name: Provisionning webservers group
  hosts: webservers
  become: yes
  vars_files:
    - ./playbook-vars.yml
  roles:
    - user
    - tools
    - docker
    - traefik
    - watchtower
    - monitoring
