---
- name: Install some tools
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - fail2ban
    - git
    - htop
    - ntp
    - python3-pip
    - tmux
    - vim
  notify:
    - start ntp

- name: Ensure fail2ban starts on a fresh reboot
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Configure bash prompt
  copy:
    src: ../files/bash_prompt.sh
    dest: /etc/profile.d/bash_prompt.sh
    owner: root
    group: root
