---
- name: Install some tools
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - fail2ban
    - git
    - htop
    - ntp
    - python3-pip
    - tmux
    - vim
  notify:
    - start ntp

- name: Ensure fail2ban starts on a fresh reboot
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Adding .zshrc file
  template:
    src: ../templates/.zshrc.j2
    dest: "{{ home_dir }}/.zshrc"
    owner: "{{ user }}"

- name: Set zsh as default shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh
